quarkus:
  live-reload:
    instrumentation: true
  application:
    name: ckm-blog-service
  http:
    cors: true
    port: 8082
  oidc:
    auth-server-url: https://iam.martens.live/auth/realms/ckm-website
    client-id: ckm-app-client
    credentials:
      secret: secretHere
  kafka-streams:
    topics: ckm-blogs
    auto:
      offset:
        reset: earliest

kafka:
  bootstrap:
    servers: kafka:9092

mp:
  messaging:
    incoming:
      ckm-blogs-incoming:
        connector: smallrye-kafka
        topic: ckm-blogs
        group:
          id: ckm-blog-consumer


