quarkus:
  http:
    cors:
      ~: true
      origins: https://photo.martens.live, https://www.hiddenhuesphoto.com
      access-control-max-age: 24H

kafka:
  bootstrap:
    servers: kafka-cluster-kafka-brokers.event.svc.cluster.local:9092